'use client'
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Calendar from "~/components/Calendar";
import Record from "~/pages/dashboard/records";
import Spinner from "~/components/Spinner";
import { type DateTime } from "~/utils/types";


const Home: NextPage = () => {
  const [date, setDate] = useState<DateTime>({
    justDate: null,
    dateTime: null,
  })

  return (
    <>
      <Head>
        <title>PHSD App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      
      <main>
       {!date.dateTime  && <Calendar setDate={setDate} date={date} />}
       {date.dateTime && false ? (
       <Record /> 
       ) : ( <div className="flex h-screen items-center justify-center">
          <Spinner />
        </div>
        )}
      </main>
    </>
  )
};

export default Home;
